### PR TITLE
change the About section also made improve the projects section to ad…

### PR DESCRIPTION
**Pull request by DhruvSeth18**
Hey @Arun100203 ,
Updated the About section layout and added a scrollable Projects section to accommodate more projects.

Screenshot 2024-10-23 175651
Screenshot 2024-10-23 175525
Screenshot 2024-10-23 175552

### CODE REVIEW

**Comment by DhruvSeth18** [comment]
@Arun100203  done with the changes , if you like this please merge my PR,
Thank you

**Comment by DhruvSeth18** [comment]
@Arun100203

**Comment by DhruvSeth18** [comment]
@Arun100203

**Comment by DhruvSeth18** [comment]
@Arun100203

**Comment by Arun100203** [comment]
Yeah @DhruvSeth18 , looks good. I will merge the PR

**Pull request merged**
